"""replace jti with token_hash in refresh_tokens

Revision ID: af3af8775350
Revises: 503271d5582f
Create Date: 2026-10-02 10:58:20.357278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af3af8775350'
down_revision: Union[str, Sequence[str], None] = '503271d5582f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('jti', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
