"""revert to jti uuid pk in refresh_tokens

Revision ID: baf0d4a32f66
Revises: af3af8775350
Create Date: 2026-10-02 11:15:52.106720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'baf0d4a32f66'
down_revision: Union[str, Sequence[str], None] = 'af3af8775350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('jti', sa.Uuid(), nullable=False))
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'jti')
    # ### end Alembic commands ###
